// define size of the board; recommended range is 3..7
const SIZE = 5;
// define whether joker is active or not; defaults to _false_ for _even_ board sizes
const USE_JOKER = false;

// define captions
var headerText = "<img src='img/htwsaar.png' alt='htw saar' />&nbsp;Vorlesungs-Bingo";
var footerText = "Jegliche Ähnlichkeiten zu real existierenden Personen sind rein zufällig.";

// ...and additional texts
var winText = "Gewonnen!";
var jokerText = "JOKER";
var flavOptText = "Spielvariante: "

// define sounds
var clickSnd = new Audio("audio/click.mp3");
var winSnd = new Audio("audio/win.mp3");

// define square texts
var JSONBingo = {"squares": 
[
	{"square":"Kubernetes","flavors":["Buzzwords"]},
	{"square":"Sprint","flavors":["Buzzwords"]},
	{"square":"Agil","flavors":["Buzzwords"]},
	{"square":"Scrum","flavors":["Buzzwords"]},
	{"square":"Cyber","flavors":["Buzzwords"]},
	{"square":"Crypto","flavors":["Buzzwords"]},
	{"square":"Cloud","flavors":["Buzzwords"]},
	{"square":"Blockchain","flavors":["Buzzwords"]},
	{"square":"App","flavors":["Buzzwords"]},
	{"square":"SEO","flavors":["Buzzwords"]},
	{"square":"Künstliche Intelligenz","flavors":["Buzzwords"]},
	{"square":"Big Data","flavors":["Buzzwords"]},
	{"square":"Machine Learning","flavors":["Buzzwords"]},
	{"square":"Metaverse","flavors":["Buzzwords"]},
	{"square":"SaaS","flavors":["Buzzwords"]},
	
	{"square":"\"Ich kam nicht in die Session rein.\"","flavors":["Sitzung"]},
	{"square":"\"Kannst du bitte größer machen?\"","flavors":["Sitzung"]},
	{"square":"\"Wer tippt denn da ständig?\"","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"\"Könnt ihr meinen Bildschirm sehen?\"","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"\"Oh, ich war ja auf stumm geschaltet!\"","flavors":["Sitzung"]},
	{"square":"\"Man hört nichts, du bist stumm geschaltet!\"","flavors":["Sitzung"]},
	{"square":"\"Schaltet euch bitte alle stumm!\"","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"\"X schreibt mir gerade bei WhatsApp.\"","flavors":["Sitzung"]},
	{"square":"\"X wählt sich gerade ein, wir warten noch kurz.\"","flavors":["Sitzung"]},
	{"square":"\"Weiß jemand, ob X noch kommt?\"","flavors":["Sitzung"]},
	{"square":"\"Man sieht nur grau.\"","flavors":["Sitzung"]},
	{"square":"\"Könnt Ihr mich hören?\"","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"\"Hallo, ist schon jemand da?\"","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"\"Wer fehlt denn noch?\"","flavors":["Sitzung"]},
	{"square":"\"Mein Mikro war stumm geschaltet.\"","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"\"Sprichst du mit uns?\"","flavors":["Sitzung"]},
	{"square":"\"Upps, ich bin eben rausgeflogen.\"","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"\"Mein Netz ist schwach.\"","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"\"X hat die Konferenz verlassen\"","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"\"Wer leitet eigentlich die Besprechung?\"","flavors":["Sitzung"]},
	{"square":"*Tastatur hämmert wie ein MG*","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"*Viele reden durcheinander*","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"*Kind wird beim Namen gerufen*","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"*Kind läuft durch das Bild*","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"*Es gibt eine Rückkopplung*","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"*Stille*","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"*Geschrei im Hintergrund*","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"*Hund bellt*","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"*Schweres Atmen*","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"*Vogel&hyphen;gezwitscher*","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"*Jemand isst/trinkt*","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"*Etwas knistert*","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"*Jemand gähnt in die Kamera*","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"*Die Augen von jemandem wandern hin und her*","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"\"BigBlueButton ist super.\"","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"\"Freiheit von Forschung und Lehre.\"","flavors":["Sitzung"]},
	{"square":"\"Die Studierenden beteiligen sich nicht.\"","flavors":["Online-Vorlesung"]},
	{"square":"\"Könnte bitte mal jemand sein Mikrofon einschalten?\"","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"\"Kann man das geteilte Fenster sehen?\"","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"*Jemand flucht über Microsoft*","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"*Ein Laptop-Lüfter dröhnt wie ein LKW*","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"*Im Hintergrund singt ein Kind*","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"\"Du bist etwas unscharf.\"","flavors":["Sitzung"]},
	{"square":"\"Das haben wir schon immer so gemacht.\"","flavors":["Sitzung"]},
	{"square":"\"Wir brauchen eine detaillierte Handreichung.\"","flavors":["Sitzung"]},
	{"square":"\"Ich habe n Überstunden.\"","flavors":["Sitzung"]},
	{"square":"\"Das geht nicht.\"","flavors":["Sitzung"]},
	{"square":"\"Mir sind die Hände gebunden.\"","flavors":["Sitzung"]},
	{"square":"\"Die da oben.\"","flavors":["Sitzung"]},
	{"square":"\"Par ordre du mufti.\"","flavors":["Sitzung"]},
	{"square":"\"X ist nicht vergnügungs&hyphen;steuerpflichtig.\"","flavors":["Sitzung"]},
	{"square":"\"Wie sieht eigentlich der Plan für X aus?\"","flavors":["Sitzung"]},
	{"square":"\"Man muss Ross und Reiter kennen.\"","flavors":["Sitzung"]},
	{"square":"\"Das ist alles wischi-waschi.\"","flavors":["Sitzung"]},
	{"square":"\"Grundrechte sind Grundrechte.\"","flavors":["Sitzung"]},
	{"square":"\"Ähm.\"","flavors":["Online-Vorlesung","Sitzung"]},
	{"square":"*AWP | Dragon Lore wird erwaehnt*","flavors":["PIB2017"]},
	{"square":"*Fnord*","flavors":["PIB2017"]},
	{"square":"*Taleb wird erwaehnt*","flavors":["PIB2017"]},
	{"square":"*Millienials-Bashing*","flavors":["PIB2017"]},
	{"square":"*Referenz auf 80er-Jahre-Action-Film*","flavors":["PIB2017"]},
	{"square":"*Schwarzenegger wird erwaehnt*","flavors":["PIB2017"]},
	{"square":"*Ein anderer Dozent wird namentlich genannt*","flavors":["PIB2017"]},
	{"square":"*Master wird erwaehnt*","flavors":["PIB2017"]},
	{"square":"*M macht einen Gamerwitz*","flavors":["PIB2017"]},
	{"square":"*M macht einen Informatikerwitz*","flavors":["PIB2017"]},
	{"square":"*Es wird gedenglischt*","flavors":["PIB2017"]},
	{"square":"*Weapons of Mass Disctraction wird erwaehnt*","flavors":["PIB2017"]},
	{"square":"*Datenschutz wird erwaehnt*","flavors":["PIB2017"]},
	{"square":"*Digitalisierung wird erwaehnt*","flavors":["PIB2017"]},
	{"square":"*BWL-Online-Vorlesung wird erwaehnt*","flavors":["PIB2017"]},
	{"square":"*Es wird in den Folien zurueckgesprungen*","flavors":["PIB2017"]},
	{"square":"*Kombiuebung*","flavors":["PIB2017"]},
	{"square":"*Comic/Bild auf Folie*","flavors":["PIB2017"]},
	{"square":"*Jemand geht frueher*","flavors":["PIB2017"]},
	{"square":"*M traegt eine Krawatte*","flavors":["PIB2017"]},
	{"square":"*Google/Facebook oder Amazon werden erwaehnt*","flavors":["PIB2017"]},
	{"square":"*M spricht jemand mit Nachnamen an*","flavors":["PIB2017"]},
	{"square":"*M erzaehlt von CS:GO*","flavors":["PIB2017"]},
	{"square":"\"Denken sie drueber nach\"","flavors":["PIB2017"]},
	{"square":"*M spricht ueber sein Arbeitsleben*","flavors":["PIB2017"]},
	{"square":"*M schweift ab*","flavors":["PIB2017"]},
	{"square":"*M gibt Tipps fuers Leben*","flavors":["PIB2017"]},
	{"square":"*Es wird diskutiert*","flavors":["PIB2017"]},
	{"square":"*Trump wird erwaehnt*","flavors":["PIB2017"]},
	{"square":"*Auf der Folie ist ein Pfeildiagramm*","flavors":["PIB2017"]},
	{"square":"*M erzaehlt ueber Lehrbuecher*","flavors":["PIB2017"]},
	{"square":"*Steam wird erwaehnt*","flavors":["PIB2017"]},
	{"square":"*Sparkasse wird erwaehnt*","flavors":["PIB2017"]},
	{"square":"*Tafel wird benutzt*","flavors":["PIB2017"]},
	{"square":"\"Sie haben noch gar nix gesagt\"","flavors":["PIB2017"]},
	{"square":"\"Wer braucht noch Zeit?\"","flavors":["PIB2017"]},
	{"square":"\"Genau\"","flavors":["PIB2017"]},
	{"square":"\"Aspekt\"","flavors":["PIB2017"]},
	{"square":"\"Relevant\"","flavors":["PIB2017"]},
	{"square":"\"Kunden\"","flavors":["PIB2017"]},
	{"square":"\"Techies\"","flavors":["PIB2017"]},
	{"square":"\"Prozesse\"","flavors":["PIB2017"]},
	{"square":"\"Koennen Sie sich in Ruhe durchlesen\"","flavors":["PIB2017"]},
	{"square":"\"Gibts noch Fragen?\"","flavors":["PIB2017"]},
	{"square":"*Klausur o. Uebungsblatt werden erwaehnt*","flavors":["PIB2017"]},
	{"square":"\"Da habense auch recht\"","flavors":["PIB2017"]},
	{"square":"*M bricht Diskussion ab*","flavors":["PIB2017"]},
	{"square":"*Nach diskussionsabbruch wird weiter diskutiert*","flavors":["PIB2017"]},
	{"square":"*Jemand kommt zu spaet(ab 5 Minuten)*","flavors":["PIB2017"]},
	{"square":"*Bulletpoints auf Folie*","flavors":["PIB2017"]},
	{"square":"\"Wollen sie noch was ergaenzen?\"","flavors":["PIB2017"]},
	{"square":"*Lieblingsfach BWL/Winfo*","flavors":["PIB2017"]},
	{"square":"*M traegt eine seiner farbigen englischen Hosen (blau/rot/gruen)*","flavors":["PIB2017"]},
	{"square":"\"Haben Sie noch 'ne Idee?\"","flavors":["PIB2017"]},
	{"square":"*Frueher war alles besser*","flavors":["PIB2017"]},
	{"square":"*Betrieblicher Umsatzprozess wird erwaehnt*","flavors":["PIB2017"]},
	{"square":"\"Einen wunderschönen guten Morgen\"","flavors":["PIB2017"]}
	]
};
